# Generated by Django 4.2.7 on 2023-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_packagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='daysdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('activity2', models.CharField(blank=True, max_length=50, null=True)),
                ('disp2', models.CharField(blank=True, max_length=50, null=True)),
                ('activity1', models.CharField(blank=True, max_length=50, null=True)),
                ('disp1', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='packagedb',
            name='activitie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
