# Generated by Django 4.2.7 on 2023-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_daysdb_alter_packagedb_activitie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysdb',
            name='activity2',
        ),
        migrations.RemoveField(
            model_name='daysdb',
            name='disp2',
        ),
        migrations.AddField(
            model_name='daysdb',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
